FSA-GRP1-2001/instastack

server/api/index.js, server/api/projects.js, server/api/users.js
=> projects route started

script/seed.js, server/api/projects.js, server/api/users.js, server/api/users.spec.js, server/db/models/index.js
I will resolve this PR's merge conflicts.
But routes for users creating projects, and viewing all of a user's projects and project's users are written in here.
also the get single user route is fixed here.
=> User project

client/components/navbar.js
=> Feature: add logout

server/api/projects.js
=> Feature(projects): add and remove users from proj routes

script/seed.js, server/db/models/component.js
=> added more components to seed file

client/components/MainPage.js, client/components/preview/DropWrapper.js, client/components/preview/Preview.js, package-lock.json, package.json, public/style.css
* [x ] add grid based drop area in place of previous demo drop area component
=> Drop area update

client/components/ClipButton.js, client/components/CodeBox/index.js, client/components/navbar.js
=> Feature: Clipboard Button

client/components/list/DragWrapper.js, client/components/list/componentSection.js, client/components/preview/Preview.js
* [x ] add sample droppable container element.  Add new draggable wrapper and use in List items component.
=> Feature: update draggable wrapper and add demo drop container

.merge_file_H7IsJG, .merge_file_mG3Xqx, .merge_file_xRQMc9, client/components/ButtonBar.js, client/components/Profile.js, client/components/ProfileProjects.js, client/components/ProfileSecurity.js, client/components/index.js, client/components/list/DragWrapper.js, client/components/navbar.js, client/components/user-home.js, client/routes.js, client/store/index.js, client/store/projects.js, client/store/users.js, server/api/projects.js, server/api/users.js
=> Wed profile

client/components/CodeBox/index.js, client/components/list/DragWrapper.js, client/components/list/componentSection.js, client/components/preview/DropWrapper.js, client/components/preview/Preview.js, client/store/code.js, package-lock.json, package.json
=> Draggable components

script/seed.js, server/db/models/component.js, server/db/models/index.htm
=> refactor: add contentTag to Component Model - Requires run seed

.gitignore, client/components/list/DragWrapper.js
=> (feat: drag and drop) - removed the appended DOM node if drag fails

client/components/ClipButton.js
feat(clip-button): user can copy whatever code is in the user state oo the clip board
Fixes #28 
Uses React useEffect hook. Depends on Redux store's code and the state.code reducer.
=> feat(clip-button): user can copy whatever code to clipboard

client/components/ClipButton.js, package-lock.json, package.json
New dependency, run npm install for the animations in Prime React for these toast notifications
=> Clip button

client/components/list/DragWrapper.js, client/components/list/componentSection.js, script/seed.js, server/db/models/component.js
update components schema
add additional logic for creating draggable components as dom nodes
=> Feature: pull components from db and update model

client/components/Profile.js, client/components/ProfileProjects.js, client/components/ProfileSecurity.js, client/components/navbar.js, client/components/user-home.js, client/routes.js, client/store/users.js, server/api/users.js
WIP: Sort out issues eager loading projects for the User Profile Projects' View.
- Routes are working: user/:id/projects and user/:id
- GetSingleUser Thunk works for User Projects' view/ component with workaround 'userId: id.id' The projects do not load though. The corresponding projects only render on state execution but do not appear on prev and next state.
- Also, the workaround for the thunk ('userId: id.id') will cause issues in the future. For example, when trying to reach the user projects' page from another component where the id is passed correctly. We need to figure out why we are passing {id: id} vs. the id itself and correct this for the thunk to work in al instances.
=> Profile rev

client/components/user-home.spec.js
update the tests for user-home
=> Fix: user-home test should get user displayName

client/components/ProfileProjects.js, client/components/TemplateHP.js, client/components/TemplateHome.js, client/components/index.js, client/components/navbar.js, client/components/user-home.js, client/routes.js
=> Simple template homepage made

client/components/CodeBox/index.js, client/components/MainPage.js, client/components/preview/Container.js, client/components/preview/DropWrapper.js, client/components/preview/Preview.js, client/store/index.js, client/store/usedComponents.js
Added remove and edit icons to containers.  Made function that returns the containers so that these items can more easily be added.
=> Feature(containers): add remove and edit icons to containers

client/components/MainPage.js, client/components/ProfileProjects.js, client/components/preview/Preview.js, client/store/containers.js, client/store/currentProject.js, client/store/usedComponents.js
update grid behavior
add remove button that removes used component and item's container
use project Id in thunk to get saved project
=> Grid fixes

client/components/ButtonBar.js, client/components/list/DragWrapper.js, client/components/list/componentSection.js, client/components/preview/DropWrapper.js, client/components/preview/Preview.js, client/components/preview/SideBar.js, client/store/currentProject.js, client/store/index.js, client/store/sidebar.js, client/store/usedStyles.js, script/seed.js, server/db/models/project.js
Add styling menu to edit basic components and small set of stylings
Add usedStyles to DB projects model
Add save and load styles to respective thunks
Add load stylings to apply saved styles to dom elements
Add save button that saves the used styles
Add updateCode to run after componentDidMount so code area populates with code after a project is done loading 
update seed data so Cody starts off with project with components in project called First Demo
TBC
Cancel button will revert unsaved stylings
Closing sidebar will also revert unsaved stylings
=> Styling menu

client/components/preview/SideBar.js
Added functions to handle cancel button and onClose event for the sidebar which restores the original styling to the selected component
=> Style menu button actions

client/components/ButtonBar.js, client/components/ClipButton.js, client/components/MainPage.js, client/components/ShowCodeMirror.js, client/components/index.js, client/components/navbar.js, client/store/index.js, client/store/showCodeMirror.js, public/style.css
=> Monday button

client/store/code.js
refactor(redux-code): enabled a lint rule, moved constants around for refactor
=> refactor(redux-code): enabled a lint rule

client/components/ClipButton.js, client/components/CodeBox/index.js, client/components/MainPage.js, client/components/list/DragWrapper.js, client/components/list/componentSection.js, public/style.css
Preview components turned into buttons that are spaced appropriately.
=> Preview buttons

client/components/BlogTemplate.js, client/components/BlogTemplatePreview.js, client/components/LandingPageTemplate.js, client/components/LandingPageTemplatePreview.js, client/components/TemplateHome.js, client/components/index.js, client/routes.js
=> Test template

client/components/ButtonBar.js
=> Fix: remove log

client/components/ButtonBar.js, client/components/ClipButton.js, client/components/MainPage.js, client/components/ShowCodeMirror.js, client/components/list/componentSection.js, client/components/preview/Preview.js, client/components/preview/SideBarMenu.js, client/components/preview/SideBarParent.js, public/style.css, script/seed.js
Add the image component edit options to sidebar
Add 'preview' button to show Preview area without blue boxes
=> More styling

public/index.html
If approved, this PR will put the favicon up on Heroku
=> hotfix: brackets now correct

client/components/preview/Preview.js
The edit icon was hard for users to notice. Now they cannot miss it!
=> feature(edit-icon): Edit icon now a gigantic spinning pencil

client/components/preview/Preview.js
fix(icon size): made them bigger and not spin
=> fix(icon size): made them bigger and not spin

client/index.js
=> Remove DND provider from index.js

client/app.js, client/components/MainPage.js, client/components/navbar.js, client/components/preview/Preview.js, public/style.css
I am making a PR for this push.
=> Start updating layout and styles

client/components/preview/Preview.js, client/components/preview/SideBarMenu.js
you can center things now
make color picker the same line as its label
=> Feature: add centering options

client/components/navbar.js, public/style.css
Links styled as buttons with color and alternate colors on mouse over
=> feat(nav-bar): Top nav bar lifted up, links styled

client/components/BlogTemplatePreview.js, client/components/CodeBox/SlidingCodePane.js, client/components/MainPage.js, client/components/ShowCodeMirror.js, package-lock.json, package.json
add sliding pane and connect code toggle to it
=> Feature: add sliding pane for code mirror viewing

client/components/navbar.js
style(log-in): buttons added to links when logging in
Buttons are styled.
=> style(log-in): buttons added to links when logging in

public/style.css
Buttons on log in are styled
Buttons lose focus halo
=> style(buttons): lose focus halo after click

client/components/ButtonBar.js, client/components/ClipButton.js, client/components/GuestHome.js, client/components/MainPage.js, client/components/ShowCodeMirror.js, client/components/navbar.js, client/components/preview/Preview.js, public/style.css
Remove conditional grid styling in MainPage so sliding pane does not change layout
Update borders in RGL and Preview area
Make buttons square and add icons
Shorten button names for copy and show code
Continue updating guest home page
=> Styles: update button bar and guest home

client/components/list/componentSection.js, script/seed.js, server/db/models/component.js
give proper names for components in the left bar
=> Update display names for left component bar

client/components/navbar.js
HOTFIX: toUpperCase on null was crashing site
This PR will fix the heroku site and any local dev servers you are trying to run off the current state of master.
=> HOTFIX: toUpperCase on null was crashing site

client/components/list/DragWrapper.js, client/components/preview/SideBarParent.js
fix button sizing and saving items after editing style
=> Fix button sizing and item saving

public/style.css
style(main-splash): blue field is pixel-perfect level with the purple side bar
=> style(main-splash): blue field is pixel-perfect level 

public/style.css
style(grey-box): grey box  surrounds main page
Previous CSS accidentally cut it off at 720px, sorry about that
=> style(grey-box): grey box  surrounds main page

client/components/ButtonBar.js
No longer is saving disabled until a user presses enter, putting any title in
allows the project to be saved.
=> feature(save-projects): UX improvement, allow save on any title

client/components/navbar.js, public/style.css
=> Navbar: add projects to drop-down

client/components/ButtonBar.js
=> HOTFIX: commenting out the growl had problems! Fixed now

client/components/preview/SideBarMenu.js, client/store/code.js, client/store/usedComponents.js
add saving text content changes
=> Fix: save basic text content changes

client/components/CodeBox/SlidingCodePane.js, client/components/preview/Preview.js, client/components/preview/SideBarMenu.js
add larger text input for para edit menu
make list items populate as list items when loading saved project
=> Edit menu fixes

client/components/navbar.js, client/routes.js, client/store/user.js, package-lock.json, server/auth/github.js, server/auth/google.js
when the user logs in he/ she lands on mainPage (DnD)
Templates btn on navbar links to home page
=> Nav links and login redirect 

client/components/preview/SideBarMenu.js, client/components/preview/SideBarParent.js, client/store/usedComponents.js
add edit fields for list items
make list items savable
update sidebar scroll styling
=> List items

client/components/ProfileProjects.js, client/components/ProfileSecurity.js, client/store/usedComponents.js
add extra check so projects link does not break app
=> Profile fixes

client/components/preview/Preview.js, client/components/preview/SideBarMenu.js, client/components/preview/SideBarParent.js
removing scroll on sidebar and replacing list items menu with collapsable group
make sure centered styles are loaded
=> Save styles

client/components/ButtonBar.js
=> feature(toast): makes toast for user on project creation and save.

client/components/preview/Preview.js
fix images loading with saved % width
=> Fix: load images with saved width

README.md
=> slight changes

client/components/ProfileProjects.js, client/components/ProfileSecurity.js, public/style.css
Add 'profile' link on projects view
Add 'projects' link on profile view
Update button's style on both profile and projects view
=> User Profile & Projects links, and btns look & feel

client/components/preview/SideBarParent.js
=> Fix: reset selectIdx after sidebar is closed
